---
abstract: 'Perl bindings to the Git linkable library (libgit2)'
author:
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '2.07'
  File::Slurp::Tiny: '0.001'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Spec::Unix: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  Time::Local: '0'
  perl: '5.006'
configure_requires:
  Devel::CheckLib: '0.6'
  ExtUtils::Constant: '0.23'
  ExtUtils::MakeMaker: 6.63_03
  File::Basename: '2.74'
  Getopt::Long: '2.35'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Raw
requires:
  Carp: '0'
  XSLoader: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jacquesg/p5-Git-Raw/issues
  homepage: http://metacpan.org/release/Git-Raw/
  repository: git://github.com/jacquesg/p5-Git-Raw.git
version: '0.50'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::ALEXBIO/GatherDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ALEXBIO/PruneCruft'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ALEXBIO/ManifestSkip'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ALEXBIO/MetaYAML'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ALEXBIO/License'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ALEXBIO/Readme'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::ALEXBIO/ExtraTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ALEXBIO/ExecDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ALEXBIO/ShareDir'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ALEXBIO/Manifest'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ALEXBIO/TestRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ALEXBIO/ConfirmRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Author::ALEXBIO/@GitHub/GitHub::Meta'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::ALEXBIO/@GitHub/GitHub::Update'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: 0.01
          version_by_branch: '0'
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ALEXBIO/Git::NextVersion'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ALEXBIO/MetaConfig'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::ALEXBIO/MetaJSON'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ALEXBIO/AutoPrereqs'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@Author::ALEXBIO/PodVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::ALEXBIO/PkgVersion'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::ALEXBIO/NextRelease'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::ALEXBIO/Test::Compile'
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::ALEXBIO/Test::CheckManifest'
      version: '0.04'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ALEXBIO/PodSyntaxTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ALEXBIO/PodCoverageTests'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ALEXBIO/Git::Commit'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.50
          tag_format: v%v
          tag_message: '%N %v'
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ALEXBIO/Git::Tag'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Author::ALEXBIO/Git::Push'
      version: '2.023'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ALEXBIO/UploadToCPAN'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ALEXBIO/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::ALEXBIO/Clean'
      version: '0.07'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: configure
          type: requires
      name: ConfigureRequires
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '5.019'
    -
      class: inc::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: MakeMaker
      version: ~
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.019'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.019'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.019'
